# Generated by Django 5.0.3 on 2024-04-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('has_DataSet', models.BooleanField(default=False)),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StarWarsCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField(null=True)),
                ('mass', models.FloatField(null=True)),
                ('hair_color', models.CharField(max_length=50, null=True)),
                ('skin_color', models.CharField(max_length=50, null=True)),
                ('eye_color', models.CharField(max_length=50, null=True)),
                ('birth_year', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('homeworld', models.CharField(max_length=100, null=True)),
                ('species', models.CharField(max_length=100, null=True)),
                ('films', models.JSONField(null=True)),
                ('vehicles', models.JSONField(null=True)),
                ('starships', models.JSONField(null=True)),
            ],
        ),
    ]
